apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: cpu.rules
      rules:
        - alert: ClusterHighCPUUsage
          expr: |
            (
              1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m]))
            ) * 100 > 60
          for: 20s
          labels:
            severity: warning
          annotations:
            summary: "CPU usage élevé sur le cluster"
            description: "L'utilisation CPU moyenne du cluster est à {{ $value | printf \"%.1f\" }}%."

        - alert: ClusterCriticalCPUUsage
          expr: |
            (
              1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m]))
            ) * 100 > 70
          for: 20s
          labels:
            severity: critical
          annotations:
            summary: "CPU critique sur le cluster"
            description: "L'utilisation CPU moyenne du cluster est à {{ $value | printf \"%.1f\" }}%."
