---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path # Classe de stockage par défaut K3s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-pvc
  namespace: minecraft

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 10Gi
