---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: backend
spec:
  encryptedData:
    backend-app-key: AgA43WEHX1Jsx5wa3aJPa3gdmgcV1b0XJxzoT/bPGKoMo3+ZEMtPHKCtCa9X9XVe5K9CUtT6A0JprpRw3xb0NierAGBTOCGOLWZIhdgqy7jBCOuOIcDH63ZE+R0FD4/lD0vlXknFQcwdowdUBAwSBEtw4q8wXX8t5JQ4fQmBlFI5/UlFt0V1IIBbvN4y/qx2DTR9QGwpC6Mvzp2JCwd9UGp09RV+3dGE5kwiVwclv0WsF/h8Ig5ozXmUjnGyk40Xpw1ldvzhEDaXYM3J1YJolBsANfDi2LJEvOLwC7Yxn/xxRC0f3NqrQBkiv+SVyW6YeqyNn/WxCLqoevBXctz/VR1F8Ev1Utf0Qcn+ussQGb7j+r9548AKtldPEIIBzw6GaOGjpvij2CnKtB3F98eiLf2GOtSraxjIQ6ROO/Tq1gsmaNfoeBDNw+91I++5n+UUMbJTIG60gq306oz/EzClLknRgAPQZKaiFiv1/qT2skI3F/eknvrm+0BNMY1ME798SWDsWDonVx1HqK0eUkIX3fmPb5ImDn042pO7P1LiiIPBVdEBz3Feem+yikVHRQts3gluBEAvUyFpDqMBn77tIlpwu00KtMa8n4bFIwf9zWVxYfkTgjsKsgUZHgAbfKr5hBYY0Um2/HFRhqxGHQBA+BnvZ9n2IRWrHNeDu943584Sb0E+8RjVskRn49jjKOOfLKwBTs0zNVWANXC8v1A7OFmQh8EtjajRWFm90xHovd649w==
  template:
    metadata:
      name: backend-secrets
      namespace: backend